import React, { useState, useEffect } from "react";
import Head from "next/head";
import { getSortedPostsData } from "../lib/posts";
import { getViews } from "../lib/firebase";
import Footer from "./Footer";
import Divider from "./Divider";

export default function IndexPage() {
  const [, setViews] = useState(0);

  const currentYear = new Date().getFullYear();

  useEffect(() => {
    fetchViews();
  }, []);

  const fetchViews = async () => {
    const views = await getViews("gpa");
    setViews(views);
  };

  const containerStyle = {
    marginTop: "auto",
    marginBottom: "auto",
    paddingTop: "1rem",
    paddingBottom: "1rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
  };

  const textContainerStyle = {
    maxWidth: "650px",
    margin: "0 auto",
    paddingTop: "3rem",
    paddingBottom: "3rem",
  };

  const mediaQueryStyle = `
    @media only screen and (max-width: 768px) {
      #text-container {
        max-width: 90%;
        padding-top: 0;
      }
      .main-container {
        padding-top: 0.5rem;
      }
    }
  `;

  return (
    <div className="main-container" style={containerStyle}>
      <style>{mediaQueryStyle}</style>
      <Head>
        <title>Wesley Tian</title>
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:url" content="wesleytian.com" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Wesley's Personal Website" />
        <meta
          property="og:description"
          content="Welcome to my personal site."
        />
        <meta property="og:image" content={"/posts/ogimage.jpeg"} />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </Head>

      <main id="text-container" style={textContainerStyle}>
        <div>
          <div styles={{ float: "left" }}></div>
          {/* <h4>Hey, I'm Wesley! 👋🏻 </h4> */}
          <div style={{ marginBottom: '1.5rem' }}>
            <img 
              src="/IMG_1901.jpeg" 
              alt="Wesley Tian" 
              // title="This photo was generated by Aragon AI"
              style={{ 
                width: '120px', 
                height: '120px', 
                borderRadius: '50%', 
                objectFit: 'cover',
                objectPosition: 'top center',
                border: '2px solid #e0e0e0',
                float: 'right',
                marginLeft: '1rem',
                marginBottom: '0.5rem'
              }} 
            />
          </div>
          <p>
          <span style={{ }}>I'm Wesley Tian, the Co-Founder and CEO of <a target="_blank" href="https://www.aragon.ai/">
                   Aragon AI
                  </a> – an AI photo platform that's generated 40M+ photos for 2.3M+ users.</span>
          </p>
          <p>I care about craft, building great businesses, and rapid growth – professional and personal.</p>
          {/* <p>
          We started by building the world’s most popular AI headshot generator (2M+ users) and have since expanded into enterprise solutions for Fortune 500s and a growing platform of AI photo products spanning photo editing and photo generation.
          </p> */}
          <p>
          Since launching in 2023, we've scaled Aragon to over 8-figures in annual run rate (ARR) and profitability, serving enterprise clients on 6-figure annual contracts. Our 12-person team includes multiple ex-founders, AI researchers, International Math Olympiad medalists, and alumni from MIT, Meta, Google, and Brex. 

          </p>
          <p>Our investors include <a target="_blank" href="https://www.neo.com/">
                   Neo
                  </a>, <a target="_blank" href="https://www.sequoiacap.com/">
                    Sequoia
                  </a> (Scout), and the founders and CEOs of multiple publicly-traded companies and unicorns.
          </p>
            <p style={{ fontWeight: 500 }}>Selected press:</p>
            <ul>
            
          <li>
              <a target="_blank" href="https://www.theinformation.com/articles/why-early-stage-founders-are-opting-to-seed-strap-their-startups">
                The Information
              </a> (2025): Why Early-Stage Founders Are Opting to 'Seed-Strap' Their Startups
            </li>
            <li>
              <a target="_blank" href="https://www.indiehackers.com/post/tech/building-one-of-the-first-ai-headshot-products-and-hitting-900k-mo-in-3-years-UK9omiPofFtha5Kps2Fj">
                Indie Hackers
              </a> (2025): Building one of the first AI headshot products and hitting $900k/mo
            </li>
            {/* <li>
              <a target="_blank" href="https://www.washingtonpost.com/technology/2024/02/08/ai-professional-headshots/">
                The Washington Post
              </a> (2024): AI professional headshots are quick and easy...
            </li> */}
            <li>
              <a target="_blank" href="https://www.businessinsider.com/why-aragon-ai-founder-chose-startup-accelerator-neo-over-ycombinator">
                Business Insider
              </a> (2023): Why I turned down Y Combinator for Neo
            </li>
            </ul>
            {/* <li><a href="https://leanaileaderboard.com/" target="_blank">
              Lean AI Leaderboard
            </a></li> */}
            {/* <li>
              <a target="_blank" href="https://bigthink.com/business/anatomy-ai-startup-key-lessons-first-time-founders/">
                Big Think
              </a>: <i>Key lessons for first-time founders</i>
            </li> */}
            {/* <li>
              <a target="_blank" href="https://youtu.be/hMvnKX0yeJw?si=Ct3p_dtDjUzXE1D7&t=1141">
                My First Million Podcast
              </a>
            </li> */}
            {/* <li>
              <a target="_blank" href="https://www.pmf.show/1st-time-founder-grows-ai-headshot-app-from-0-to-10m-arr-in-2-years-with-no-funding-wesley-tian/">
                The Product Market Fit Show Podcast
              </a>
            </li> */}
            {/* <li>
              <a target="_blank" href="https://open.spotify.com/episode/6dyNbnylQwTeEGhyyIb0Li?si=X7DOG9_YRDaLbLwQrKxW4w">
                NeuralZen Venture Podcast
              </a>
            </li> */}

         

         

          {/* <p>
            Before starting Aragon, I was a founding engineer at two {" "}
            <a
              target="_blank"
              href="https://aws.amazon.com/startups/learn/a-cup-of-innovation-chatting-with-startup-founders-at-their-favorite-cafs?sc_channel=sm&sc_publisher=LINKEDIN&sc_country=global&sc_geo=GLOBAL&sc_outcome=awareness&linkId=691394166"
            >
              Y Combinator
            </a>
            -backed startups, a software engineer at Microsoft, an machine learning engineer at Clinc AI, and an AI
            researcher at the University of Michigan.
          </p> */}
          {/* <hr></hr> */}
          {/* <p style={{ fontWeight: 500 }}>Hobbies:</p> */}
         
          {/* <p>Besides working out to optimize my overall health, I also enjoy mountaineering, skiing, and endurance sports when I have the time.</p> */}
          {/* <p>Some physical goals and achievements of mine:</p> */}
          {/* <ul style={{ listStyle: 'none', paddingLeft: 0 }}>
           
            {/* <li>
              <input type="checkbox" style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Climb an 8,000-meter peak
            </li> */}
           
           
            {/* <li>
              <input type="checkbox" defaultChecked style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Learn to do a standing backflip (2024)
            </li>
            <li>
              <input type="checkbox" defaultChecked style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Learn to do muscle-ups
            </li>
            <li>
              <input type="checkbox" defaultChecked style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Bench press 225 lbs.
            </li> */}
            {/* <li>
              <input type="checkbox" defaultChecked style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Finish a 140.6-mile Ironman Triathlon
            </li>
            <li>
              <input type="checkbox" defaultChecked style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Climb Mt. Kilimanjaro 
            </li>
            {/* <li>
              <input type="checkbox" defaultChecked style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Climb Mt. Whitney (2019)
            </li>
            <li>
              <input type="checkbox" defaultChecked style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Climb Mt. Fuji (2015)
            </li>
            */}
            {/* <li>
              <input type="checkbox" defaultChecked style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Run a sub-5 min mile
            </li>
            <li>
              <input type="checkbox" style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Climb Mt. Rainier
            </li>
            <li>
              <input type="checkbox" style={{ marginRight: '0.5rem', cursor: 'pointer' }} />
              Climb Mt. Everest
            </li> */}
            
          {/* </ul> */}
          <p>
            I'm an angel investor and LP in 15+ companies and VC funds, including <a target="_blank" href="https://neo.com/">
                    Neo
                  </a> and <a target="_blank" href="https://www.openai.com/">
                    OpenAI
                  </a>.
                
          </p>
          <p>
           Outside of work, I enjoy mountaineering, skiing, and endurance sports. I've finished a 140.6-mile Ironman triathlon, climbed Mt. Kilimanjaro, and ran a sub-6 minute mile. Mt. Rainier and Everest are on the list.
          </p>
      
          {/* 🏔️ I enjoy climbing mountains. Here are a few notable
          experiences (click to expand):
          <ul>
            <details>
              <summary style={{ cursor: "pointer" }}>
                Mt. Kilimanjaro (19,341 ft / 5,895 m)
              </summary>
              <p>
                In January 2025, I organized 3 friends to climb the tallest
                mountain in Africa. It took us 5 days to summit and 2 days to
                descend. One of us was unable to summit due to altitude sickness
                which caused debilitating headaches, diarrhea, nausea, and
                extreme fatigue among us. At that extreme elevation, only ~50%
                of the oxygen at sea level was available to us.
              </p>
              <p>
                Early in the climb, I got severe food poisoning. At one point,
                even water made me have explosive diarrhea. Despite that, I
                still had to hike through blistering sun, rain, sleet, stinging
                hail, and snow. Summit day started at 10 p.m., and we ended up
                hiking 17 hours that day. This was the most physical suffering
                I've ever endured–even more than my Ironman.
              </p>
            </details>
            <details>
              <summary style={{ cursor: "pointer" }}>
                Mt. Whitney (14,505 ft / 4,421 m)
              </summary>
              <p>
                In 2019, I organized three friends to climb the tallest mountain
                in the contiguous US. We started the climb at 2 am, and it took
                us 17 hours to summit and descend. People usually split this
                climb into two days. We ran out of water near the summit, so one
                of us had to drink piss to survive (we filtered it).
              </p>
            </details>
            <details>
              <summary style={{ cursor: "pointer" }}>
                Mt. Fuji (12,389 ft / 3,776 m)
              </summary>
              <p>
                In 2015, I organized 3 friends to "bullet climb" the tallest
                mountain in Japan, which means to summit and descend in a single
                push without staying overnight on the mountain. It took us 14
                hours total. It’s now forbidden to bullet climb Mt. Fuji because
                too many people have been injured from attempting it. My friends
                stopped hiking after this experience because of how challenging
                it was.
              </p>
            </details>
          </ul>
          <p>
            I've wanted to climb the Seven Summits (the highest mountain on each
            continent, including Mt. Everest) ever since I was a kid. I’ve
            conquered one so far and have six more to go.
          </p>
          <p>
            🚴🏻 In 2021, I trained for and completed an Ironman Triathlon–a
            140.6-mile (226 km) endurance race consisting of a 2.4-mile swim, a
            112-mile bike ride, and a 26.2-mile marathon, all done back-to-back,
            in Cozumel, Mexico, where it was 80&deg;F (27&deg;C) with 100%
            humidity.
          </p>
          <p>
            Right after I crossed the finish line, I collapsed from <a target="_blank" href="https://en.wikipedia.org/wiki/Hyponatremia">hyponatremia </a> 
             and had to be carried away on a stretcher. For the first time in my
            life, I was scared that I had irreversibly fucked up my body–my
            entire body was cramping, including my face, and I couldn't even
            open my fists. The race took me 15 hours to finish and it was the
            hardest physical thing I've ever done.
          </p> */}
          {/* <p>
            💪🏻 I've also trained to do a muscle-up, land a standing backflip,
            and bench press two plates (225 lbs / 102 kg).
          </p> */}
          {/* <hr></hr> */}
          <p style={{ fontWeight: 400 }}>Fun facts:</p>
          <ul>
            <li>
              I was born in Mountain View, CA and grew up near San
              Francisco, in Oregon, Taiwan, and Shanghai.
            </li>
            
            <li>
              I'm in a Netflix documentary called{" "}
              <a target="_blank" href="https://www.netflix.com/title/81757532">
                Don't Die
              </a>
              
              .
             
             
            </li> <li>I've visited ~30 countries and 6 continents.</li>
            {/* <li>I got a 1.9 GPA during high school.</li> */}
            {/* <br/>
              High school was formative for me:
            <li>
              When I was 15, I attended a military camp in Kentucky. They shaved our heads as soon as we arrived, none of the bathroom stalls had doors, they made a guy run until he puked because he took too long to finish eating, I ate some ants, we had to wake up every morning at 4:30 a.m. to do physical training (PT), and more. The camp shut down soon after I left due to safety concerns and lawsuits filed against them.
            </li>
           
            <li> I
            was the worst League of Legends player in my grade and I wanted to be the best, so I put over a thousand hours into the game and eventually made it to semi-pro.
            </li>
            <li>
            I had a 1.9/4.0 GPA (C- average) during my junior year and I graduated at the bottom of my class. <a href="/posts/gpa">Blog Post</a></li>
            <li>I competed on 6 sports teams–track, cross country, tennis, table tennis, swimming, and basketball.</li>
            
             */}
          
          </ul>
          {/* <p>
            Here are my socials:{" "}
            <a href="https://x.com/wesleyytian" target="_blank">
              X
            </a>{" "}
            and{" "}
            <a href="https://www.linkedin.com/in/wesleytian/" target="_blank">
              LinkedIn
            </a>.
            
          </p> */}
          {/* <p>Thanks for reading,</p>
          <p>Wesley Tian</p> */}
          <a href="mailto:wesley@aragon.ai">wesley@aragon.ai</a>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();

  return {
    props: {
      allPostsData,
    },
  };
}

